prepend:
  - 'DOMAIN-SUFFIX,store.steampowered.com,ğŸ”° èŠ‚ç‚¹é€‰æ‹©'
  - 'DOMAIN-SUFFIX,steamcommunity.com,ğŸ”° èŠ‚ç‚¹é€‰æ‹©'
  - 'DOMAIN-SUFFIX,steamstatic.com,ğŸ”° èŠ‚ç‚¹é€‰æ‹©'
  - 'DOMAIN-SUFFIX,api.steampowered.com,ğŸ”° èŠ‚ç‚¹é€‰æ‹©'
  - 'DOMAIN-SUFFIX,monica.im,ğŸ”° èŠ‚ç‚¹é€‰æ‹©'
  - 'DOMAIN-SUFFIX,beddystories.com,ğŸ”° èŠ‚ç‚¹é€‰æ‹©'
  - 'DOMAIN-SUFFIX,mistral1.ai,ğŸ¯ å…¨çƒç›´è¿,no-resolve'
  - 'DOMAIN-SUFFIX,mistral.ai,ğŸ”° èŠ‚ç‚¹é€‰æ‹©'
  - 'DOMAIN-SUFFIX,huggingface.co,ğŸ”° èŠ‚ç‚¹é€‰æ‹©'
  - 'DOMAIN-SUFFIX,dify.ai,ğŸ”° èŠ‚ç‚¹é€‰æ‹©'
  - 'DOMAIN-SUFFIX,openrouter.co,ğŸ¯ å…¨çƒç›´è¿,no-resolve'
  - 'DOMAIN-SUFFIX,aistudio.google.com,ChatGPT'
  - 'DOMAIN-SUFFIX,cloud.google.com,ChatGPT'
  - 'DOMAIN-KEYWORD,generativelanguage,ChatGPT'
  - 'DOMAIN-KEYWORD,colab,ChatGPT'
  - 'DOMAIN-SUFFIX,apis.google.com,ChatGPT'
  - 'DOMAIN-SUFFIX,googleapis.com,ChatGPT'
  - 'DOMAIN-SUFFIX,gemini.google.com,ChatGPT'
  - 'DOMAIN-KEYWORD,developerprofiles,ChatGPT'
  - 'DOMAIN-SUFFIX,ai.google.dev,ChatGPT'
  - 'DOMAIN-SUFFIX,makersuite.google.com,ChatGPT'
  - 'DOMAIN-SUFFIX,alkalicore-pa.clients6.google.com,ChatGPT'
  - 'DOMAIN-KEYWORD,alkalimakersuite-pa.clients6.google.com,ChatGPT'
  - 'DOMAIN-SUFFIX,alkalimakersuite-pa.clients6.google.com,ChatGPT'
  - 'DOMAIN-SUFFIX,generativeai.google,ChatGPT'
append: []
delete: []
