prepend:
  - 'DOMAIN-SUFFIX,store.steampowered.com,๐ฐ ่็น้ๆฉ'
  - 'DOMAIN-SUFFIX,steamcommunity.com,๐ฐ ่็น้ๆฉ'
  - 'DOMAIN-SUFFIX,monica.im,๐ฐ ่็น้ๆฉ'
  - 'DOMAIN-SUFFIX,beddystories.com,๐ฐ ่็น้ๆฉ'
append: []
delete: []
