prepend:
  - 'DOMAIN-SUFFIX,store.steampowered.com,CyberGuard'
  - 'DOMAIN-KEYWORD,steamcommunity,CyberGuard'
  - 'DOMAIN-SUFFIX,steamstatic.com,CyberGuard'
  - 'DOMAIN-SUFFIX,steam-chat.com,CyberGuard'
  - 'DOMAIN-SUFFIX,cmp3-hkg1.steamserver.net,CyberGuard'
  - 'DOMAIN-SUFFIX,api.steampowered.com,CyberGuard'
  - 'DOMAIN-SUFFIX,monica.im,CyberGuard'
  - 'DOMAIN-SUFFIX,beddystories.com,CyberGuard'
  - 'DOMAIN-SUFFIX,mistral1.ai,DIRECT,no-resolve'
  - 'DOMAIN-SUFFIX,mistral.ai,CyberGuard'
  - 'DOMAIN-SUFFIX,huggingface.co,CyberGuard'
  - 'DOMAIN-SUFFIX,dify.ai,CyberGuard'
  - 'DOMAIN-SUFFIX,aistudio.google.com,ChatGPT'
  - 'DOMAIN-SUFFIX,accounts.google.com,ChatGPT'
  - 'DOMAIN-SUFFIX,developers.google.com,ChatGPT'
  - 'DOMAIN-SUFFIX,cloud.google.com,ChatGPT'
  - 'DOMAIN-KEYWORD,generativelanguage,ChatGPT'
  - 'DOMAIN-KEYWORD,colab,ChatGPT'
  - 'DOMAIN-SUFFIX,apis.google.com,ChatGPT'
  - 'DOMAIN-SUFFIX,googleapis.com,ChatGPT'
  - 'DOMAIN-SUFFIX,gstatic.com,ChatGPT'
  - 'DOMAIN-SUFFIX,generativelanguage.googleapis.com,ChatGPT'
  - 'DOMAIN-SUFFIX,gemini.google.com,ChatGPT'
  - 'DOMAIN-KEYWORD,developerprofiles,ChatGPT'
  - 'DOMAIN-SUFFIX,ai.google.dev,ChatGPT'
  - 'DOMAIN-SUFFIX,makersuite.google.com,ChatGPT'
  - 'DOMAIN-SUFFIX,alkalicore-pa.clients6.google.com,ChatGPT'
  - 'DOMAIN-KEYWORD,alkalimakersuite-pa.clients6.google.com,ChatGPT'
  - 'DOMAIN-SUFFIX,alkalimakersuite-pa.clients6.google.com,ChatGPT'
  - 'DOMAIN-SUFFIX,generativeai.google,ChatGPT'
  - 'DOMAIN-SUFFIX,cursor.com,ChatGPT'
  - 'DOMAIN-SUFFIX,cursor.sh,ChatGPT'
  - 'DOMAIN-SUFFIX,knox.chat,DIRECT,no-resolve'
  - 'DOMAIN-SUFFIX,bigmodel.cn,DIRECT,no-resolve'
  - 'DOMAIN-SUFFIX,ping0.cc,ChatGPT'
append: []
delete: []
